import type { Metadata } from "next";
import { Inter, Noto_Serif } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbconfig";
import MainProvider from "./components/MainProvider";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Information",
  description: "Generated by Product Information",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <Header />
          <div className="text-blue-950">{children}</div>
        </MainProvider>
      </body>
    </html>
  );
}
